/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef AGENTXTUTORIAL_H
#define AGENTXTUTORIAL_H

/* function declarations */
void init_agentxTutorial(void);
Netsnmp_Node_Handler handle_myROString;
Netsnmp_Node_Handler handle_myROInteger;

#endif /* AGENTXTUTORIAL_H */
