/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "myTestTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement myTestTable get routines.
 * TODO:240:M: Implement myTestTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table myTestTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * AGENTX-TUTORIAL-MIB::myTestTable is subid 1 of myTables.
 * Its status is Current.
 * OID: .1.3.6.1.3.9999.2.1, length: 8
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement myTestTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param myROStringCol1_ptr
 * @param myROStringCol1_ptr_len
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
myTestTable_indexes_set_tbl_idx(myTestTable_mib_index *tbl_idx, char *myROStringCol1_val_ptr,  size_t myROStringCol1_val_ptr_len)
{
    DEBUGMSGTL(("verbose:myTestTable:myTestTable_indexes_set_tbl_idx","called\n"));

    /* myROStringCol1(1)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H */
    tbl_idx->myROStringCol1_len = sizeof(tbl_idx->myROStringCol1)/sizeof(tbl_idx->myROStringCol1[0]); /* max length */
    /*
     * make sure there is enough space for myROStringCol1 data
     */
    if ((NULL == tbl_idx->myROStringCol1) ||
        (tbl_idx->myROStringCol1_len <
         (myROStringCol1_val_ptr_len))) {
        snmp_log(LOG_ERR,"not enough space for value (myROStringCol1_val_ptr)\n");
        return MFD_ERROR;
    }
    tbl_idx->myROStringCol1_len = myROStringCol1_val_ptr_len;
    memcpy( tbl_idx->myROStringCol1, myROStringCol1_val_ptr, myROStringCol1_val_ptr_len* sizeof(myROStringCol1_val_ptr[0]) );
    

    return MFD_SUCCESS;
} /* myTestTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
myTestTable_indexes_set(myTestTable_rowreq_ctx *rowreq_ctx, char *myROStringCol1_val_ptr,  size_t myROStringCol1_val_ptr_len)
{
    DEBUGMSGTL(("verbose:myTestTable:myTestTable_indexes_set","called\n"));

    if(MFD_SUCCESS != myTestTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , myROStringCol1_val_ptr, myROStringCol1_val_ptr_len
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != myTestTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* myTestTable_indexes_set */


/*---------------------------------------------------------------------
 * AGENTX-TUTORIAL-MIB::myTestTableEntry.myROIntCol2
 * myROIntCol2 is subid 2 of myTestTableEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.3.9999.2.1.1.2
 * Description:
Just a test integer for table
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  0 - 2147483647;
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the myROIntCol2 data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param myROIntCol2_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
myROIntCol2_get( myTestTable_rowreq_ctx *rowreq_ctx, long * myROIntCol2_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != myROIntCol2_val_ptr );


    DEBUGMSGTL(("verbose:myTestTable:myROIntCol2_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the myROIntCol2 data.
 * copy (* myROIntCol2_val_ptr ) from rowreq_ctx->data
 */
    (* myROIntCol2_val_ptr ) = rowreq_ctx->data.myROIntCol2;

    return MFD_SUCCESS;
} /* myROIntCol2_get */



/** @} */
