/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef MYTESTTABLE_DATA_ACCESS_H
#define MYTESTTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table myTestTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * AGENTX-TUTORIAL-MIB::myTestTable is subid 1 of myTables.
 * Its status is Current.
 * OID: .1.3.6.1.3.9999.2.1, length: 8
*/


    int myTestTable_init_data(myTestTable_registration * myTestTable_reg);


    /*
     * TODO:180:o: Review myTestTable cache timeout.
     * The number of seconds before the cache times out
     */
#define MYTESTTABLE_CACHE_TIMEOUT   60

void myTestTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void myTestTable_container_shutdown(netsnmp_container *container_ptr);

int myTestTable_container_load(netsnmp_container *container);
void myTestTable_container_free(netsnmp_container *container);

int myTestTable_cache_load(netsnmp_container *container);
void myTestTable_cache_free(netsnmp_container *container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
 */
#define MAX_LINE_SIZE 256
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    int myTestTable_row_prep( myTestTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* MYTESTTABLE_DATA_ACCESS_H */
