/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef MYTESTTABLE_INTERFACE_H
#define MYTESTTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "myTestTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _myTestTable_initialize_interface(myTestTable_registration * user_ctx,
                                    u_long flags);
void _myTestTable_shutdown_interface(myTestTable_registration * user_ctx);

myTestTable_registration *
myTestTable_registration_get( void );

myTestTable_registration *
myTestTable_registration_set( myTestTable_registration * newreg );

netsnmp_container *myTestTable_container_get( void );
int myTestTable_container_size( void );

    myTestTable_rowreq_ctx * myTestTable_allocate_rowreq_ctx(void *);
void myTestTable_release_rowreq_ctx(myTestTable_rowreq_ctx *rowreq_ctx);

int myTestTable_index_to_oid(netsnmp_index *oid_idx,
                            myTestTable_mib_index *mib_idx);
int myTestTable_index_from_oid(netsnmp_index *oid_idx,
                              myTestTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void myTestTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* MYTESTTABLE_INTERFACE_H */
/** @} */
