/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/** \page MFD helper for myTestTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "myTestTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "myTestTable_interface.h"

const oid myTestTable_oid[] = { MYTESTTABLE_OID };
const int myTestTable_oid_size = OID_LENGTH(myTestTable_oid);

    myTestTable_registration  myTestTable_user_context;

void initialize_table_myTestTable(void);
void shutdown_table_myTestTable(void);


/**
 * Initializes the myTestTable module
 */
void
init_myTestTable(void)
{
    DEBUGMSGTL(("verbose:myTestTable:init_myTestTable","called\n"));

    /*
     * TODO:300:o: Perform myTestTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("myTestTable"))
        initialize_table_myTestTable();

} /* init_myTestTable */

/**
 * Shut-down the myTestTable module (agent is exiting)
 */
void
shutdown_myTestTable(void)
{
    if (should_init("myTestTable"))
        shutdown_table_myTestTable();

}

/**
 * Initialize the table myTestTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_myTestTable(void)
{
    myTestTable_registration * user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:myTestTable:initialize_table_myTestTable","called\n"));

    /*
     * TODO:301:o: Perform myTestTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize myTestTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("myTestTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _myTestTable_initialize_interface(user_context, flags);
} /* initialize_table_myTestTable */

/**
 * Shutdown the table myTestTable 
 */
void
shutdown_table_myTestTable(void)
{
    /*
     * call interface shutdown code
     */
    _myTestTable_shutdown_interface(&myTestTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
myTestTable_rowreq_ctx_init(myTestTable_rowreq_ctx *rowreq_ctx,
                           void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:myTestTable:myTestTable_rowreq_ctx_init","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:210:o: |-> Perform extra myTestTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
} /* myTestTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void myTestTable_rowreq_ctx_cleanup(myTestTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:myTestTable:myTestTable_rowreq_ctx_cleanup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:211:o: |-> Perform extra myTestTable rowreq cleanup.
     */
} /* myTestTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
myTestTable_pre_request(myTestTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:myTestTable:myTestTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform myTestTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* myTestTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
myTestTable_post_request(myTestTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:myTestTable:myTestTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform myTestTable post-request actions.
     */

    return MFD_SUCCESS;
} /* myTestTable_post_request */


/** @{ */
