/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef AGENTXTUTORIAL_TRAPS_H
#define AGENTXTUTORIAL_TRAPS_H

/* function declarations */
int send_myROIntHit_trap(int ValueForAlerting);

#endif /* AGENTXTUTORIAL_TRAPS_H */
