/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "agentxTutorial_traps.h"

extern const oid snmptrap_oid[];
extern const size_t snmptrap_oid_len;

int
send_myROIntHit_trap(int ValueForAlerting)
{
    time_t now = time(0);
    char buffer[] = "This is a test string";
    netsnmp_variable_list  *var_list = NULL;
    const oid myROIntHit_oid[] = { 1,3,6,1,3,9999,0,1 };
    const oid myTrapData_oid[] = { 1,3,6,1,3,9999,0,0,2, 0 };
    const oid myTrapTime_oid[] = { 1,3,6,1,3,9999,0,0,1, 0 };
    const oid myROInteger_oid[] = { 1,3,6,1,3,9999,1,2, 0 };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        myROIntHit_oid, sizeof(myROIntHit_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        myTrapData_oid, OID_LENGTH(myTrapData_oid),
        ASN_OCTET_STR,
        buffer,
        strlen(buffer));
    snmp_varlist_add_variable(&var_list,
        myTrapTime_oid, OID_LENGTH(myTrapTime_oid),
        ASN_INTEGER,
        &now,
        sizeof(now));
    snmp_varlist_add_variable(&var_list,
        myROInteger_oid, OID_LENGTH(myROInteger_oid),
        ASN_INTEGER,
        &ValueForAlerting,
        sizeof(ValueForAlerting));

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
