/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef MYTESTTABLE_H
#define MYTESTTABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_add_mib(AGENTX-TUTORIAL-MIB)
config_require(AGENTX-TUTORIAL-MIB/myTestTable/myTestTable_interface)
config_require(AGENTX-TUTORIAL-MIB/myTestTable/myTestTable_data_access)
config_require(AGENTX-TUTORIAL-MIB/myTestTable/myTestTable_data_get)
config_require(AGENTX-TUTORIAL-MIB/myTestTable/myTestTable_data_set)
    /* *INDENT-ON*  */

/* OID and column number definitions for myTestTable */
#include "myTestTable_oids.h"

/* enum definions */
#include "myTestTable_enums.h"

/* *********************************************************************
 * function declarations
 */
void init_myTestTable(void);
void shutdown_myTestTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table myTestTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * AGENTX-TUTORIAL-MIB::myTestTable is subid 1 of myTables.
 * Its status is Current.
 * OID: .1.3.6.1.3.9999.2.1, length: 8
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review myTestTable registration context.
     */
typedef netsnmp_data_list myTestTable_registration;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review myTestTable data context structure.
 * This structure is used to represent the data for myTestTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * myTestTable.
 */
typedef struct myTestTable_data_s {
    
        /*
         * myROIntCol2(2)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
         */
   long   myROIntCol2;
    
} myTestTable_data;


/*
 * TODO:120:r: |-> Review myTestTable mib index.
 * This structure is used to represent the index for myTestTable.
 */
typedef struct myTestTable_mib_index_s {

        /*
         * myROStringCol1(1)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
        /** 128 - 0(other indexes) - oid length(10) = 117 */
   char   myROStringCol1[117];
   size_t      myROStringCol1_len;


} myTestTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review myTestTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
     *
     * BE VERY CAREFUL TO TAKE INTO ACCOUNT THE MAXIMUM
     * POSSIBLE LENGHT FOR EVERY VARIABLE LENGTH INDEX!
     * Guessing 128 - col/entry(2)  - oid len(8)
*/
#define MAX_myTestTable_IDX_LEN     118


/* *********************************************************************
 * TODO:130:o: |-> Review myTestTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * myTestTable_rowreq_ctx pointer.
 */
typedef struct myTestTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_myTestTable_IDX_LEN];
    
    myTestTable_mib_index        tbl_idx;
    
    myTestTable_data              data;

    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * TODO:131:o: |   |-> Add useful data to myTestTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *myTestTable_data_list;

} myTestTable_rowreq_ctx;

typedef struct myTestTable_ref_rowreq_ctx_s {
    myTestTable_rowreq_ctx *rowreq_ctx;
} myTestTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int myTestTable_pre_request(myTestTable_registration * user_context);
    int myTestTable_post_request(myTestTable_registration * user_context,
        int rc);

    int myTestTable_rowreq_ctx_init(myTestTable_rowreq_ctx *rowreq_ctx,
                                   void *user_init_ctx);
    void myTestTable_rowreq_ctx_cleanup(myTestTable_rowreq_ctx *rowreq_ctx);


    myTestTable_rowreq_ctx *
                  myTestTable_row_find_by_mib_index(myTestTable_mib_index *mib_idx);

extern const oid myTestTable_oid[];
extern const int myTestTable_oid_size;


#include "myTestTable_interface.h"
#include "myTestTable_data_access.h"
#include "myTestTable_data_get.h"
#include "myTestTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* MYTESTTABLE_H */
/** @} */
