/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 * @file myTestTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef MYTESTTABLE_DATA_GET_H
#define MYTESTTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table myTestTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * AGENTX-TUTORIAL-MIB::myTestTable is subid 1 of myTables.
 * Its status is Current.
 * OID: .1.3.6.1.3.9999.2.1, length: 8
*/
    /*
     * indexes
     */

    int myROIntCol2_get( myTestTable_rowreq_ctx *rowreq_ctx, long * myROIntCol2_val_ptr );


int myTestTable_indexes_set_tbl_idx(myTestTable_mib_index *tbl_idx, char *myROStringCol1_val_ptr,  size_t myROStringCol1_val_ptr_len);
int myTestTable_indexes_set(myTestTable_rowreq_ctx *rowreq_ctx, char *myROStringCol1_val_ptr,  size_t myROStringCol1_val_ptr_len);




#ifdef __cplusplus
}
#endif

#endif /* MYTESTTABLE_DATA_GET_H */
/** @} */
