/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef MYTESTTABLE_OIDS_H
#define MYTESTTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table myTestTable */
#define MYTESTTABLE_OID              1,3,6,1,3,9999,2,1


#define COLUMN_MYROSTRINGCOL1         1
    
#define COLUMN_MYROINTCOL2         2
    

#define MYTESTTABLE_MIN_COL   COLUMN_MYROSTRINGCOL1
#define MYTESTTABLE_MAX_COL   COLUMN_MYROINTCOL2
    


#ifdef __cplusplus
}
#endif

#endif /* MYTESTTABLE_OIDS_H */
